#logging.level.root: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invest
    username: root
    password: local
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mysql:3306/invest
    username: root
    password: local
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: false
        format_sql: false
