version: '3'

services:
  db:
    image: mariadb:10.5.8
    command:
    - mysqld
    - --character-set-server=utf8
    - --collation-server=utf8_general_ci
    - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: invest
      MYSQL_ROOT_PASSWORD: local
    ports:
    - "3306:3306"

  # database management tool
  adminer:
    image: adminer
    restart: always
    ports:
    - 8090:8080
