logging.level.root: DEBUG

spring:
  profiles:
    include:
    - core

  flyway:
    enabled: true
    baseline-on-migrate: false
    url: jdbc:mysql://localhost:3306/invest
    user: root
    password: local
