#logging.level.root: DEBUG

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/invest
    username: root
    password: local
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
