version: '3'

services:
  app:
    image: reaperes/investment-analyser:0.1
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
    - 8080:8080

  mysql:
    image: mariadb:10.5.8
    command:
    - mysqld
    - --character-set-server=utf8
    - --collation-server=utf8_general_ci
    - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: invest
      MYSQL_ROOT_PASSWORD: local
    ports:
    - 3306:3306
    volumes:
    - /home/namu/data/mysql:/var/lib/mysql

  # database management tool
  adminer:
    image: adminer:4
    restart: always
    ports:
    - 8090:8080

  grafana:
    image: grafana/grafana:7.4.1
    restart: always
    ports:
    - 3000:3000
    volumes:
    - /home/namu/data/grafana:/var/lib/grafana

  nginx:
    image: staticfloat/nginx-certbot
    restart: always
    ports:
    - 80:80
    - 443:443
    environment:
      CERTBOT_EMAIL: reaperes105@gmail.com
    volumes:
    - /home/namu/data/nginx/conf.d:/etc/nginx/user.conf.d:ro
    - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
